#pragma once
// ============================================================
// LevelGenerationPipeline.h
//
// Single engine entry point for playable level generation:
//   DifficultyProfile → PLE geometry → GameplayDecorator content
//
// EngineBridge delegates here; it must not duplicate this logic.
// ============================================================

#include "Common.h"
#include "GameplayDecorator.h"
#include "PlatformerLevelEngine.h"
#include "PlayerCapabilities.h"

namespace APLG {

struct LevelGenerationStats {
    int32   jumpCount       = 0;
    float32 difficultyScore = 0.0f;
    int32   platformCount   = 0;
    bool    valid           = true;
    std::string reason      = "Generated by PLE+Decorator";
};

struct LevelGenerationResult {
    LevelData         level;
    DifficultyProfile profile;
    int32             seed = 0;
    LevelGenerationStats stats;
};

class LevelGenerationPipeline {
public:
    struct Request {
        DifficultyLevel difficulty = DifficultyLevel::Normal;
        Playstyle       playstyle  = Playstyle::Careful;
        int32           seed       = 0;   ///< 0 = derive from high-resolution clock
    };

    /**
     * @brief Generate a guaranteed-playable, fully decorated level.
     */
    static LevelGenerationResult generate(
        const Request& request,
        const Validation::PlayerCapabilities& caps);

    /**
     * @brief Build the active difficulty profile, including playstyle modifiers.
     */
    static DifficultyProfile buildProfile(DifficultyLevel difficulty,
                                          Playstyle playstyle);

    /**
     * @brief Resolve a non-zero seed when request.seed <= 0.
     */
    static int32 resolveSeed(int32 seedInOut);
};

} // namespace APLG
